// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2Up8DUmBB1Tx5dhznkvCW5
// Component: 296qaVSDm1cX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2Up8DUmBB1Tx5dhznkvCW5/projectcss
import sty from "./PlasmicButtonOutline.module.css"; // plasmic-import: 296qaVSDm1cX/css

import UpRightSvgrepoComSvgIcon from "./icons/PlasmicIcon__UpRightSvgrepoComSvg"; // plasmic-import: lJir7KSUxXWg/icon

createPlasmicElementProxy;

export type PlasmicButtonOutline__VariantMembers = {
  styles: "wide" | "blue" | "disabled";
};
export type PlasmicButtonOutline__VariantsArgs = {
  styles?: SingleChoiceArg<"wide" | "blue" | "disabled">;
};
type VariantPropType = keyof PlasmicButtonOutline__VariantsArgs;
export const PlasmicButtonOutline__VariantProps = new Array<VariantPropType>(
  "styles"
);

export type PlasmicButtonOutline__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicButtonOutline__ArgsType;
export const PlasmicButtonOutline__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicButtonOutline__OverridesType = {
  button?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultButtonOutlineProps {
  children?: React.ReactNode;
  styles?: SingleChoiceArg<"wide" | "blue" | "disabled">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicButtonOutline__RenderFunc(props: {
  variants: PlasmicButtonOutline__VariantsArgs;
  args: PlasmicButtonOutline__ArgsType;
  overrides: PlasmicButtonOutline__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "styles",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.styles
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"button"}
      data-plasmic-override={overrides.button}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.button,
        {
          [sty.buttonstyles_blue]: hasVariant($state, "styles", "blue"),
          [sty.buttonstyles_disabled]: hasVariant($state, "styles", "disabled"),
          [sty.buttonstyles_wide]: hasVariant($state, "styles", "wide")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxstyles_blue]: hasVariant($state, "styles", "blue"),
          [sty.freeBoxstyles_disabled]: hasVariant(
            $state,
            "styles",
            "disabled"
          ),
          [sty.freeBoxstyles_wide]: hasVariant($state, "styles", "wide")
        })}
      >
        {renderPlasmicSlot({
          defaultContents: "Contact sales",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenstyles_disabled]: hasVariant(
              $state,
              "styles",
              "disabled"
            ),
            [sty.slotTargetChildrenstyles_wide]: hasVariant(
              $state,
              "styles",
              "wide"
            )
          })
        })}
      </div>
      <UpRightSvgrepoComSvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgstyles_blue]: hasVariant($state, "styles", "blue"),
          [sty.svgstyles_disabled]: hasVariant($state, "styles", "disabled"),
          [sty.svgstyles_wide]: hasVariant($state, "styles", "wide")
        })}
        role={"img"}
      />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  button: ["button", "freeBox", "svg"],
  freeBox: ["freeBox"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  button: "div";
  freeBox: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonOutline__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonOutline__VariantsArgs;
    args?: PlasmicButtonOutline__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonOutline__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicButtonOutline__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButtonOutline__ArgProps,
          internalVariantPropNames: PlasmicButtonOutline__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButtonOutline__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "button") {
    func.displayName = "PlasmicButtonOutline";
  } else {
    func.displayName = `PlasmicButtonOutline.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonOutline = Object.assign(
  // Top-level PlasmicButtonOutline renders the root element
  makeNodeComponent("button"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicButtonOutline
    internalVariantProps: PlasmicButtonOutline__VariantProps,
    internalArgProps: PlasmicButtonOutline__ArgProps
  }
);

export default PlasmicButtonOutline;
/* prettier-ignore-end */
